export { enrollHandler  } from '../endpoints/enroll.js'
export { completeCourseHandler } from '../endpoints/complete-course.js'
export { completeLessonHandler } from '../endpoints/complete-lesson.js'
export { submitQuizHandler } from '../endpoints/submit-quiz.js'
export { addCertificateToUserHandler } from '../endpoints/add-certificate-to-user.js'
export { addUserToGroupHandler } from '../endpoints/add-user-to-group.js'
export { fetchProgressHandler } from '../endpoints/fetch-progress.js'
export { generateCertificateHandler } from '../endpoints/generate-certificate.js'