export { deepMerge, mergeFields, isObject, } from '../utilities/deepMerge.js'
export { findFieldByNameAndType } from '../utilities/findFieldByNameAndType.js'
export { sanitizePluginConfig } from '../utilities/sanitizePluginConfig.js'
export { getCollectionSlugMap } from '../utilities/getCollectionSlugMap.js'
export { completedLesson, lessonHasQuizzes, allQuizzesCompleted } from '../utilities/completedLesson.js'
export { isPreviousLessonCompleted } from '../utilities/isPreviousLessonCompleted.js'
export { courseCompletion } from '../utilities/courseCompletion.js'
export { courseCompletionPercentage } from '../utilities/courseCompletionPercentage.js'